# Generated by Django 3.2.7 on 2021-09-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('account', '0002_alter_account_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ManyToManyField(through='portfolio.LikePortfolio', to='portfolio.Portfolio'),
        ),
    ]
