# Generated by Django 3.2.7 on 2021-09-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=1000)),
                ('corp_code', models.CharField(max_length=100, null=True)),
                ('count_searching', models.IntegerField(default=0)),
                ('total_like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='LikeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_companies',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(through='company.LikeCompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
